# Creating numpy array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([[1,2,3],[4,5,6]])

In [4]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a

array([1, 2, 3])

In [8]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [9]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a

array([1, 2, 3])

In [16]:
a.ndim

1

In [17]:
a.shape

(3,)

In [18]:
a.size

3

In [19]:
a.itemsize

8

In [20]:
a.dtype

dtype('int64')

In [21]:
a.astype(np.int8)

array([1, 2, 3], dtype=int8)

In [23]:
np.prod(a)

np.int64(6)

In [24]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [25]:
a & b

array([[1, 2, 3],
       [0, 0, 2]])

In [26]:
np.dot(a,b)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [27]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)


In [28]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [32]:
a2 @ a3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [33]:
a = [1,2,3,4,5]

In [34]:
b = np.arange(1,6)

In [42]:
import sys

print(sys.getsizeof(a))
print(sys.getsizeof(b))
a.dtype

10000112
89095160


dtype('int8')

In [36]:
a

[1, 2, 3, 4, 5]

In [37]:
b

array([1, 2, 3, 4, 5])

In [41]:
a = np.arange(10000000,dtype=np.int8)
b = [i for i in range(10000000)]


In [43]:
a

array([  0,   1,   2, ..., 125, 126, 127], dtype=int8)

In [ ]:
from pytube import YouTube

# Function to get video duration
def get_video_duration(video_url):
    # Create a YouTube object
    yt = YouTube(video_url)

    # Get the video duration in seconds
    duration_seconds = yt.length

    # Convert seconds to hours, minutes, seconds
    hours, remainder = divmod(duration_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    # Return the duration in a formatted string
    return f"{hours}h {minutes}m {seconds}s" if hours else f"{minutes}m {seconds}s"

# Example usage
video_url = 'https://www.youtube.com/watch?v=zCDVUyq8lkw'
duration = get_video_duration(video_url)
print(f"Video Duration: {duration}")


In [46]:
!pip install pytube


In [ ]:
!pip install yt-dlp


In [48]:
import yt_dlp

# Function to get video duration using yt-dlp
def get_video_duration(video_url):
    # Setting options to extract only the metadata
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'extract_flat': True,  # This avoids downloading the video itself
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        # Extract metadata
        info_dict = ydl.extract_info(video_url, download=False)
        duration = info_dict.get('duration')

    return duration

# Example usage
video_url = 'https://www.youtube.com/watch?v=zCDVUyq8lkw'  # Replace with actual YouTube video URL
duration = get_video_duration(video_url)

# Convert duration from seconds to hours, minutes, and seconds
hours, remainder = divmod(duration, 3600)
minutes, seconds = divmod(remainder, 60)

print(f"Video Duration: {int(hours)}h {int(minutes)}m {int(seconds)}s")


ERROR: [youtube] zCDVUyq8lkw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


DownloadError: ERROR: [youtube] zCDVUyq8lkw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U